(function(){
  function render(){
    var oldHeader=document.querySelector('header');
    if(oldHeader){oldHeader.outerHTML='<header class="site-header"><div class="site-nav"><a class="site-logo" href="index.html"><img src="mehanit-logo-cropped.png" alt="Механит"></a><nav class="site-menu" aria-label="Главное меню"><a href="index.html#equipment">Оборудование</a><a href="index.html#solutions">Решения</a><a href="stock.html">Склад в РФ</a><a href="production-equipment.html">Комплексный подход</a><a href="press.html">Пресс-центр</a><a href="contacts.html">Контакты</a></nav><div class="site-actions"><a class="site-icon" href="index.html#site-search" aria-label="Поиск по сайту"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"></circle><path d="m16 16 4.5 4.5"></path></svg></a><a class="site-icon" href="mailto:info@mehanit.ru" aria-label="Написать на почту"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="1"></rect><path d="m4 7 8 6 8-6"></path></svg></a><a class="site-phone" href="tel:88005511206">8 800 55 11 206</a><button class="site-burger" type="button" aria-label="Открыть меню">☰</button></div></div></header>'}
    var shellHeader=document.querySelector('.site-header');
    var shellBurger=document.querySelector('.site-burger');
    if(shellHeader&&shellBurger){shellBurger.addEventListener('click',function(){shellHeader.classList.toggle('menu-open')})}
    var oldFooter=document.querySelector('footer');
    if(oldFooter){oldFooter.outerHTML='<footer class="site-footer"><div class="site-footer-inner"><div class="site-footer-grid"><div class="site-footer-brand"><img src="mehanit-logo-cropped.png" alt="Механит"><p>Инженерный интегратор для металлообработки. Подбор оборудования под задачу, разработка технологии, поставка, пусконаладка и сервис с 2006 года.</p></div><div><h4>Оборудование</h4><a href="equipment-turning.html">Токарное и фрезерное</a><a href="equipment-edm.html">EDM и шлифование</a><a href="equipment-boring.html">Расточные и сверлильные</a><a href="equipment-saw.html">Пилы, лазер, гидроабразив</a><a href="stock.html">Склад в России</a></div><div><h4>Компания</h4><a href="index.html#equipment">Оборудование</a><a href="index.html#solutions">Решения</a><a href="stock.html">Склад РФ</a><a href="production-equipment.html">Комплексный подход</a><a href="press.html">Пресс-центр</a></div><div><h4>Контакты</h4><a href="tel:88005511206">8 800 55 11 206</a><a href="tel:+78312820500">8 (831) 282 0500</a><a href="mailto:info@mehanit.ru">info@mehanit.ru</a><a href="contacts.html">Нижний Новгород,<br>Южное шоссе, 16В</a><p class="site-footer-req">ОГРН 1095256004370<br>ИНН 5256089670<br>КПП 525601001</p></div></div><div class="site-footer-bottom"><span>Механит · 2006–2026 · mehanit.ru</span><span>© 2026 ГК «Механит». Все права защищены.</span></div></div></footer>'}
  }
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',render)}else{render()}
})();
